/** Shared HTML shell and helpers for the static pages. Plain HTML and CSS, no framework. */

export function esc(s: string | number | bigint): string {
  return String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

const CSS = `
:root { --bg:#fbfaf7; --fg:#1d1d1b; --muted:#6b6b66; --line:#dedbd2; --bad:#a1260d; --ok:#1f6b3a; --warn:#8a5a00; --card:#ffffff; }
@media (prefers-color-scheme: dark) { :root { --bg:#161614; --fg:#ecebe6; --muted:#a3a29b; --line:#3a3934; --bad:#ff8a70; --ok:#7fd49b; --warn:#f0c060; --card:#1f1f1c; } }
* { box-sizing: border-box; }
body { margin:0; background:var(--bg); color:var(--fg); font:15px/1.5 system-ui, -apple-system, "Segoe UI", sans-serif; }
main { max-width: 980px; margin: 0 auto; padding: 24px 16px 64px; }
h1 { font-size: 1.5rem; margin: 0 0 4px; } h2 { font-size: 1.15rem; margin: 28px 0 8px; }
.sub { color: var(--muted); margin: 0 0 16px; }
.caveat { border-left: 4px solid var(--warn); background: var(--card); padding: 10px 14px; margin: 12px 0 20px; }
.grid { display:grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 12px; }
.tile { background: var(--card); border:1px solid var(--line); border-radius: 8px; padding: 12px; }
.tile .k { color: var(--muted); font-size: .85rem; } .tile .v { font-size: 1.4rem; font-variant-numeric: tabular-nums; }
.bad { color: var(--bad); } .ok { color: var(--ok); } .warn { color: var(--warn); }
table { width:100%; border-collapse: collapse; font-variant-numeric: tabular-nums; }
th, td { text-align:left; padding: 6px 8px; border-bottom: 1px solid var(--line); vertical-align: top; }
td.n, th.n { text-align: right; }
.scroll { overflow-x: auto; }
code { font-size: .85em; word-break: break-all; }
footer { margin-top: 40px; color: var(--muted); font-size: .85rem; }
`;

export function page(title: string, body: string): string {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(title)}</title>
<style>${CSS}</style>
</head>
<body><main>
${body}
<footer>Generated by the apex CLI from register state. All entities and figures in the demo are simulated.</footer>
</main></body>
</html>
`;
}

export function tile(k: string, v: string, cls = ""): string {
  return `<div class="tile"><div class="k">${esc(k)}</div><div class="v ${cls}">${v}</div></div>`;
}
